sudo: required

language: java

services:
  - docker
  
before_install:
    #- chmod +x mvnw
    - docker build -t sinch5/spring-cloud-config-server -f ./spring-cloud-config-server/Dockerfile.dev ./spring-cloud-config-server
    - docker build -t sinch5/spring-cloud-config-server -f ./netflix-eureka-naming-server/Dockerfile.dev ./netflix-eureka-naming-server

script:
    - docker run sinch5/spring-cloud-config-server mvn test
    - docker run sinch5/netflix-eureka-naming-server mvn test
    
after_success:
    - docker build -t sinch5/spring-cloud-config-server .
    - docker build -t sinch5/netflix-eureka-naming-server .
      #Loginto docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take thos image and push them to gitgub
    - docker push sinch5/spring-cloud-config-server
    - docker push sinch5/netflix-eureka-naming-server
    
deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: mostviews
    env: Mostviews-env
    bucket_name: elasticbeanstalk-us-east-1-608067911170
    bucket_path: config-server
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY