sudo: required

language: java

services:
  - docker
  
before_install:
    #- chmod +x mvnw
    - docker build -t sinch5/spring-cloud-config-server -f ./spring-cloud-config-server/Dockerfile.dev ./spring-cloud-config-server
    - docker build -t sinch5/netflix-eureka-naming-server -f ./netflix-eureka-naming-server/Dockerfile.dev ./netflix-eureka-naming-server
    - docker build -t sinch5/netflix-zuul-api-gateway-server -f ./netflix-zuul-api-gateway-server/Dockerfile.dev ./netflix-zuul-api-gateway-server
    - docker build -t sinch5/places-service -f ./places-service/Dockerfile.dev ./places-service
    - docker build -t sinch5/place-details-service -f ./place-details-service/Dockerfile.dev ./place-details-service
    - docker build -t sinch5/distance-matrix-service -f ./distance-matrix-service/Dockerfile.dev ./distance-matrix-service
    - docker build -t sinch5/path-finder-service -f ./path-finder-service/Dockerfile.dev ./path-finder-service    
        

script:
    - docker run sinch5/spring-cloud-config-server mvn test
    - docker run sinch5/netflix-eureka-naming-server mvn test
    - docker run sinch5/netflix-zuul-api-gateway-server mvn test
    - docker run sinch5/places-service mvn test
    - docker run sinch5/place-details-service mvn test
    - docker run sinch5/distance-matrix-service mvn test
    - docker run sinch5/path-finder-service mvn test
    
    
after_success:
    - docker build -t sinch5/spring-cloud-config-server ./spring-cloud-config-server
    - docker build -t sinch5/netflix-eureka-naming-server ./netflix-eureka-naming-server
    - docker build -t sinch5/netflix-zuul-api-gateway-server ./netflix-zuul-api-gateway-server
    - docker build -t sinch5/places-service ./places-service
    - docker build -t sinch5/place-details-service ./place-details-service
    - docker build -t sinch5/distance-matrix-service ./distance-matrix-service
    - docker build -t sinch5/path-finder-service ./path-finder-service
   
      #Loginto docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take thos image and push them to gitgub
    - docker push sinch5/spring-cloud-config-server
    - docker push sinch5/netflix-eureka-naming-server
    - docker push sinch5/netflix-zuul-api-gateway-server
    - docker push sinch5/places-service
    - docker push sinch5/place-details-service
    - docker push sinch5/distance-matrix-service
    - docker push sinch5/path-finder-service
    
deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: mostviews
    env: Mostviews-env-2
    bucket_name: elasticbeanstalk-us-east-1-608067911170
    bucket_path: config-server
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY