apiVersion: v1
kind: Service
metadata:
    name: config-server-port
spec:
    type: NodePort
    ports:
      - port: 8050
        targetPort: 8888
        nodePort: 31515
    selector:
        component: web