apiVersion: v1
kind: Pod
metadata:
    name: config-server
    labels:
        component: web
spec:
    containers:
      - name: client
        image: sinch5/spring-cloud-config-server
        ports:
            - containerPort: 8888