apiVersion: apps/v1
kind: Deployment
metadata:
	name: config-server-deployment
spec:
	replicas: 1
	selector:
		matchLabels:
			component: web
	template:
		metadata:
			labels:
				component: web
		spec:
			containers:
				- name: client
					image: sinch5/spring-cloud-config-server
					ports:
						- containerPort: 3000
						